### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by xarg** [Briskine/briskine#214]
In a RTL (Right-To-Left) environment like arabic and hebrew the icon is placed in the right side of the input area. We need to place it on the other side of the screen by detecting the browser `dir='rtl'` for example or have an option in the settings. I prefer an automatic method.

This will require some work with the positioning calculation of the dialog.

Also needs RTL support in the right text editor.

**Comment by xarg** [comment]
@ghinda seems this was released no? https://twitter.com/briskineapp/status/1417410601257783303

**Comment by ghinda** [comment]
@xarg There are still some improvements required for the dialog positioning on RTL. That's why I'm leaving it open for now.
