### ISSUE TITLE
Missing tags from exported templates

### ISSUE THREAD

**Issue by ezeparziale** [Briskine/briskine#470]
#### Description

- When export template to csv, the file doesnt contain tags column

#### Steps to reproduce:

1. Select all template
2. export templates
3. open csv
4. column missing: tags

only columns: id,title,shortcut,subject,cc,bcc,to,body

**Comment by ghinda** [comment]
Hi, thanks for reporting the issue. 
We've had to temporarily remove the tags from the exported file, as we made a revamp on how we handle them.

We'll add the tags be back to the `csv` soon.

**Comment by ghinda** [comment]
Tags are now back in the exported `csv` file. They also get created when imported.
