### ISSUE TITLE
Paragraph size

### ISSUE THREAD

**Issue by ezeparziale** [Briskine/briskine#479]
#### Description

In paragraph, when a choose a font type then in size selector cant define a pt size. Only 100%, 75%..... 
For example I need to define 12pt.

**Comment by ghinda** [comment]
Hi there,

We've switched from fixed font sizes (like pt) to the percentage-based relative ones to improve compatibility with mobile email clients.
For example, previously when using pt-based font sizes, text from Briskine templates could have a different size on Gmail desktop, and the Gmail Android/iOS app. 

Using percentages fixes that and makes sure the templates you insert look ok wherever your emails are viewed.
