### ISSUE TITLE
UX improvement: Add a link to the github repo on https://app.briskine.com/list

### ISSUE THREAD

**Issue by DanKaplanSES** [Briskine/briskine#489]
### Why we need it

- At the moment, it takes me a lot of steps to figure out how to create a github issue because I look for a link to github on https://app.briskine.com/list until I've looked/clicked enough to conclude it's not there, then do a Google search to find it.

### What we need

- Perhaps a link to the github repo could be placed in this menu:

![image](https://user-images.githubusercontent.com/373675/208192434-895adaad-95cd-4bea-a7f2-e3e118389ecb.png)

**Comment by ghinda** [comment]
We've added details about the open source license, and GitHub links, in the Help Center:
https://help.briskine.com/
